OPEN_STATUS = "open"
IN_PROGRESS_STATUS = "in_progress"
BLOCKED_STATUS = "blocked"
CLOSED_STATUS = "closed"

TICKET_ALLOWED_STATUSES = {
    OPEN_STATUS,
    IN_PROGRESS_STATUS,
    BLOCKED_STATUS,
    CLOSED_STATUS,
}

PARENT_ALLOWED_STATUSES = {
    OPEN_STATUS,
    IN_PROGRESS_STATUS,
    CLOSED_STATUS,
}